### ISSUE TITLE
NoSuchFieldError: Handle

### ISSUE THREAD

**Issue by Emptyless** [0x6a77/JD2XX#8]
I am using the Openhab2 RFXCom binding and used the jar from `/prebuilt-jnilibs` with the `/prebuilt-jnilibs/arm-hf/ ` shared library. Unfortunately I get the error: 

```
Caused by: java.lang.NoSuchFieldError: handle
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)[:1.8.0_121]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)[:1.8.0_121]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)[:1.8.0_121]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)[:1.8.0_121]
	at java.lang.System.loadLibrary(System.java:1122)[:1.8.0_121]
	at jd2xx.JD2XX.<clinit>(JD2XX.java:727)
```

**Comment by astopaolo** [comment]
I've the same problem
